from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Sequence

from app.agent.state import TaskSnapshot
from app.artifact_validation import ArtifactValidationContext
from app.contracts.interfaces import ArtifactStore
from app.contracts.models import ArtifactManifest, TaskContext
from app.core.workspace import safe_join
from app.rag.models import ClaimProvenance, EvidenceItem

logger = logging.getLogger(__name__)

# Key the grounded answer generator is expected to populate on ``final_result``.
# Producing this data is Joy's job; this handler only carries it.
CALCULATIONS_FIELD = "calculations"

# The wire shape is dictated by ``CalculationSpec`` in
# app/runtime/generators/docx.py:38, which is a strict pydantic model
# (extra="forbid"). It is stricter than what the validator reads at
# app/artifact_validation/validator.py:274-277, so this handler validates
# against the strict shape: a looser payload would pass the validator and then
# fail the DOCX build with VALIDATION_ERROR.
#
#   {"name": str, "formula": str, "inputs": {str: str}, "result": str}
#
# The validator coerces with float(), so string-encoded numbers are correct here.
_REQUIRED_CALCULATION_KEYS = ("name", "formula", "inputs", "result")


def _validated_calculations(answer: dict[str, Any], task_id: str) -> list[dict[str, Any]]:
    """Extract well-formed calculations, failing closed on anything malformed.

    Entries are normalized down to exactly ``_REQUIRED_CALCULATION_KEYS`` because
    the DOCX spec forbids extra keys, and anything that is not a well-formed
    strict entry is dropped rather than forwarded. Dropping is the fail-closed
    behaviour: a calculation that cannot be verified never reaches a deliverable,
    and a malformed one can never abort the artifact build.
    """
    if CALCULATIONS_FIELD not in answer:
        logger.info(
            "grounded answer carries no calculations field; artifact will declare none",
            extra={"task_id": task_id},
        )
        return []
    raw = answer[CALCULATIONS_FIELD]
    if not isinstance(raw, (list, tuple)):
        logger.warning(
            "grounded answer calculations field is %s, not a list; dropping all",
            type(raw).__name__,
            extra={"task_id": task_id},
        )
        return []
    accepted: list[dict[str, Any]] = []
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            logger.warning(
                "dropping calculation %d: not an object (%s)", index, type(item).__name__,
                extra={"task_id": task_id},
            )
            continue
        name = item.get("name")
        formula = item.get("formula")
        inputs = item.get("inputs")
        result = item.get("result")
        if not isinstance(name, str) or not name.strip():
            logger.warning(
                "dropping calculation %d: name must be a non-empty string", index,
                extra={"task_id": task_id},
            )
            continue
        if not isinstance(formula, str) or not formula.strip():
            logger.warning(
                "dropping calculation %d: formula must be a non-empty string", index,
                extra={"task_id": task_id},
            )
            continue
        if not isinstance(inputs, dict) or not all(
            isinstance(key, str) and isinstance(value, str) for key, value in inputs.items()
        ):
            logger.warning(
                "dropping calculation %d: inputs must map strings to strings", index,
                extra={"task_id": task_id},
            )
            continue
        if not isinstance(result, str) or not result.strip():
            logger.warning(
                "dropping calculation %d (%s): result must be a non-empty string; "
                "the DOCX spec does not accept a bare number",
                index, name,
                extra={"task_id": task_id},
            )
            continue
        accepted.append(
            {"name": name, "formula": formula, "inputs": dict(inputs), "result": result}
        )
    if not accepted and raw:
        logger.warning(
            "every calculation was malformed; artifact will declare none",
            extra={"task_id": task_id},
        )
    return accepted


class GroundedAnswerArtifactHandler:
    """Creates a deterministic DOCX approval note from citation-verified claims."""

    def __init__(self, artifact_store: ArtifactStore) -> None:
        self.artifact_store = artifact_store
        self._contexts: dict[str, ArtifactValidationContext] = {}
        self._task_contexts: dict[str, TaskContext] = {}

    async def repair(self, task: TaskSnapshot, validation: Any) -> ArtifactManifest:
        """Regenerate the artifact from the same citation-verified inputs.

        The regenerated bytes are re-validated by the caller, so a repair can
        never move an artifact to APPROVAL without a fresh VALID verdict.
        """
        context = self._contexts.get(task.task_id)
        task_context = self._task_contexts.get(task.task_id)
        if context is None or task_context is None:
            raise ValueError("no verified artifact context is available to repair from")
        if not isinstance(task.final_result, dict) or not isinstance(task.final_result.get("answer"), str):
            raise ValueError("grounded answer is unavailable for repair")
        claims = [ClaimProvenance.model_validate(item) for item in context.claims]
        return await self.create(
            task, task_context, claims, list(context.evidence), list(context.citation_results)
        )

    async def create(
        self,
        task: TaskSnapshot,
        context: TaskContext,
        claims: Sequence[ClaimProvenance],
        evidence: Sequence[EvidenceItem],
        citation_results: Sequence[Any],
    ) -> ArtifactManifest:
        answer = task.final_result
        if not isinstance(answer, dict) or not isinstance(answer.get("answer"), str):
            raise ValueError("grounded answer is unavailable")
        if task.verification_status != "passed":
            raise ValueError("grounded answer has not passed citation verification")
        if context.task_id != task.task_id:
            raise ValueError("task context ID does not match the task")
        if task.workspace is not None and Path(context.workspace).resolve() != task.workspace.resolve():
            raise ValueError("task context workspace does not match the task workspace")

        evidence_by_id = {item.chunk_id: item for item in evidence}
        results_by_claim: dict[str, list[Any]] = {}
        for result in citation_results:
            if not result.verified:
                raise ValueError("unverified citations cannot be included in an artifact")
            results_by_claim.setdefault(result.claim_id, []).append(result)

        verified_claims: list[dict[str, Any]] = []
        verification_provenance = []
        evidence_provenance = []
        findings: list[str] = []
        citation_ids: list[str] = []
        spec_evidence: dict[str, dict[str, Any]] = {}
        for claim in claims:
            associated = [evidence_by_id.get(chunk_id) for chunk_id in claim.evidence_chunk_ids]
            if not associated or any(item is None for item in associated):
                raise ValueError("claim references unknown evidence")
            results = results_by_claim.get(claim.claim_id, [])
            verified_chunks = {item.evidence.chunk_id for item in results if item.verified}
            if verified_chunks != set(claim.evidence_chunk_ids):
                raise ValueError("every claim evidence reference must have a successful citation result")
            verified_claims.append({
                "claim_id": claim.claim_id,
                "text": claim.claim,
                "evidence_chunk_ids": list(claim.evidence_chunk_ids),
                "verification_ids": sorted({result.verification.verification_id for result in results}),
            })
            findings.append(f"[{claim.claim_id}] {claim.claim}")
            citation_ids.extend(claim.evidence_chunk_ids)
            for item in associated:
                if item is None:
                    continue
                spec_evidence[item.chunk_id] = {
                    "chunk_id": item.chunk_id,
                    "document_id": item.document_id,
                    "page": max(1, item.page or 1),
                    "section": item.section or "Unspecified",
                    "source_hash": item.source_hash,
                }
            verification_provenance.extend(result.verification for result in results)
            evidence_provenance.extend(result.evidence for result in results)

        outputs = safe_join(context.workspace, "outputs")
        outputs.mkdir(parents=True, exist_ok=True)
        path = safe_join(outputs, "grounded-answer.docx")
        from app.runtime.generators.docx import generate as generate_docx

        calculations = _validated_calculations(answer, task.task_id)
        sections = [
            {"heading": "Verified Findings", "paragraphs": findings, "citations": sorted(set(citation_ids))},
            {"heading": "Citation Verification", "paragraphs": [
                f"{item['claim_id']} / {item['chunk_id']}: verified"
                for item in sorted(({
                    "claim_id": result.claim_id,
                    "chunk_id": result.evidence.chunk_id,
                } for result in citation_results), key=lambda item: (item["claim_id"], item["chunk_id"]))
            ]},
            {"heading": "Grounded Analysis", "paragraphs": [answer["answer"]]},
        ]
        spec_evidence_sorted = sorted(spec_evidence.values(), key=lambda item: item["chunk_id"])
        spec = {
            "title": "Inspection Approval Note",
            "metadata": {
                "task_id": task.task_id,
                "verification_status": "passed",
                "generated_at": "deterministic-content",
                "content_hash": "computed-by-generator",
            },
            "sections": sections,
            "evidence": spec_evidence_sorted,
            "calculations": calculations,
            "assumptions": ["Only citation-verified claims are presented as findings."],
            "recommendation": answer["answer"],
        }
        content_hash = generate_docx(path, spec)
        manifest = await self.artifact_store.register(
            context,
            "docx",
            str(path),
            source_evidence_ids=sorted(spec_evidence),
            metadata={
                "content_type": "grounded_answer",
                "verification_status": "passed",
                "content_hash": content_hash,
                "spec": {
                    "title": "Inspection Approval Note",
                    "metadata": {"task_id": task.task_id, "verification_status": "passed"},
                    "sections": sections,
                    "evidence": spec_evidence_sorted,
                    "calculations": calculations,
                    "assumptions": ["Only citation-verified claims are presented as findings."],
                    "recommendation": answer["answer"],
                },
            },
        )
        self._contexts[task.task_id] = ArtifactValidationContext(
            claims=tuple(claims), evidence=tuple(evidence),
            citation_results=tuple(citation_results),
            verifications=tuple(verification_provenance),
            expected_fields=("title", "sections", "evidence", "recommendation"),
            calculations=tuple(calculations),
            provenance=tuple({
                "document_id": item.document_id,
                "chunk_id": item.chunk_id,
                "source_hash": item.source_hash,
                "claim_id": item.claim_id,
                "verification_id": item.verification_id,
                "artifact_id": manifest.artifact_id,
            } for item in evidence_provenance),
        )
        self._task_contexts[task.task_id] = context
        return manifest

    def validation_context(self, task_id: str) -> ArtifactValidationContext | None:
        return self._contexts.get(task_id)
